/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as _rootErrorRouteImport } from './routes/__root.error'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardScheduleRouteImport } from './routes/dashboard/schedule'
import { Route as DashboardProfileRouteImport } from './routes/dashboard/profile'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard/notifications'
import { Route as DashboardAvailableRouteImport } from './routes/dashboard/available'
import { Route as DashboardShiftsIndexRouteImport } from './routes/dashboard/shifts/index'
import { Route as DashboardBusinessesIndexRouteImport } from './routes/dashboard/businesses/index'
import { Route as ApiShiftsIndexRouteImport } from './routes/api/shifts/index'
import { Route as DashboardShiftsNewRouteImport } from './routes/dashboard/shifts/new'
import { Route as DashboardShiftsIdRouteImport } from './routes/dashboard/shifts/$id'
import { Route as DashboardBusinessesNewRouteImport } from './routes/dashboard/businesses/new'
import { Route as DashboardBusinessesIdRouteImport } from './routes/dashboard/businesses/$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiShiftsIdClaimsRouteImport } from './routes/api/shifts/$id/claims'

const _rootErrorRoute = _rootErrorRouteImport.update({
  id: '/__root/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardScheduleRoute = DashboardScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAvailableRoute = DashboardAvailableRouteImport.update({
  id: '/available',
  path: '/available',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardShiftsIndexRoute = DashboardShiftsIndexRouteImport.update({
  id: '/shifts/',
  path: '/shifts/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBusinessesIndexRoute =
  DashboardBusinessesIndexRouteImport.update({
    id: '/businesses/',
    path: '/businesses/',
    getParentRoute: () => DashboardRoute,
  } as any)
const ApiShiftsIndexRoute = ApiShiftsIndexRouteImport.update({
  id: '/api/shifts/',
  path: '/api/shifts/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardShiftsNewRoute = DashboardShiftsNewRouteImport.update({
  id: '/shifts/new',
  path: '/shifts/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardShiftsIdRoute = DashboardShiftsIdRouteImport.update({
  id: '/shifts/$id',
  path: '/shifts/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBusinessesNewRoute = DashboardBusinessesNewRouteImport.update({
  id: '/businesses/new',
  path: '/businesses/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBusinessesIdRoute = DashboardBusinessesIdRouteImport.update({
  id: '/businesses/$id',
  path: '/businesses/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShiftsIdClaimsRoute = ApiShiftsIdClaimsRouteImport.update({
  id: '/api/shifts/$id/claims',
  path: '/api/shifts/$id/claims',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/error': typeof _rootErrorRoute
  '/dashboard/available': typeof DashboardAvailableRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/schedule': typeof DashboardScheduleRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/businesses/$id': typeof DashboardBusinessesIdRoute
  '/dashboard/businesses/new': typeof DashboardBusinessesNewRoute
  '/dashboard/shifts/$id': typeof DashboardShiftsIdRoute
  '/dashboard/shifts/new': typeof DashboardShiftsNewRoute
  '/api/shifts/': typeof ApiShiftsIndexRoute
  '/dashboard/businesses/': typeof DashboardBusinessesIndexRoute
  '/dashboard/shifts/': typeof DashboardShiftsIndexRoute
  '/api/shifts/$id/claims': typeof ApiShiftsIdClaimsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/error': typeof _rootErrorRoute
  '/dashboard/available': typeof DashboardAvailableRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/schedule': typeof DashboardScheduleRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/businesses/$id': typeof DashboardBusinessesIdRoute
  '/dashboard/businesses/new': typeof DashboardBusinessesNewRoute
  '/dashboard/shifts/$id': typeof DashboardShiftsIdRoute
  '/dashboard/shifts/new': typeof DashboardShiftsNewRoute
  '/api/shifts': typeof ApiShiftsIndexRoute
  '/dashboard/businesses': typeof DashboardBusinessesIndexRoute
  '/dashboard/shifts': typeof DashboardShiftsIndexRoute
  '/api/shifts/$id/claims': typeof ApiShiftsIdClaimsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/__root/error': typeof _rootErrorRoute
  '/dashboard/available': typeof DashboardAvailableRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/schedule': typeof DashboardScheduleRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/businesses/$id': typeof DashboardBusinessesIdRoute
  '/dashboard/businesses/new': typeof DashboardBusinessesNewRoute
  '/dashboard/shifts/$id': typeof DashboardShiftsIdRoute
  '/dashboard/shifts/new': typeof DashboardShiftsNewRoute
  '/api/shifts/': typeof ApiShiftsIndexRoute
  '/dashboard/businesses/': typeof DashboardBusinessesIndexRoute
  '/dashboard/shifts/': typeof DashboardShiftsIndexRoute
  '/api/shifts/$id/claims': typeof ApiShiftsIdClaimsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/error'
    | '/dashboard/available'
    | '/dashboard/notifications'
    | '/dashboard/profile'
    | '/dashboard/schedule'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/api/auth/$'
    | '/dashboard/businesses/$id'
    | '/dashboard/businesses/new'
    | '/dashboard/shifts/$id'
    | '/dashboard/shifts/new'
    | '/api/shifts/'
    | '/dashboard/businesses/'
    | '/dashboard/shifts/'
    | '/api/shifts/$id/claims'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/login'
    | '/signup'
    | '/error'
    | '/dashboard/available'
    | '/dashboard/notifications'
    | '/dashboard/profile'
    | '/dashboard/schedule'
    | '/dashboard/settings'
    | '/dashboard'
    | '/api/auth/$'
    | '/dashboard/businesses/$id'
    | '/dashboard/businesses/new'
    | '/dashboard/shifts/$id'
    | '/dashboard/shifts/new'
    | '/api/shifts'
    | '/dashboard/businesses'
    | '/dashboard/shifts'
    | '/api/shifts/$id/claims'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/__root/error'
    | '/dashboard/available'
    | '/dashboard/notifications'
    | '/dashboard/profile'
    | '/dashboard/schedule'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/api/auth/$'
    | '/dashboard/businesses/$id'
    | '/dashboard/businesses/new'
    | '/dashboard/shifts/$id'
    | '/dashboard/shifts/new'
    | '/api/shifts/'
    | '/dashboard/businesses/'
    | '/dashboard/shifts/'
    | '/api/shifts/$id/claims'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  _rootErrorRoute: typeof _rootErrorRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiShiftsIndexRoute: typeof ApiShiftsIndexRoute
  ApiShiftsIdClaimsRoute: typeof ApiShiftsIdClaimsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/__root/error': {
      id: '/__root/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof _rootErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/schedule': {
      id: '/dashboard/schedule'
      path: '/schedule'
      fullPath: '/dashboard/schedule'
      preLoaderRoute: typeof DashboardScheduleRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/available': {
      id: '/dashboard/available'
      path: '/available'
      fullPath: '/dashboard/available'
      preLoaderRoute: typeof DashboardAvailableRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/shifts/': {
      id: '/dashboard/shifts/'
      path: '/shifts'
      fullPath: '/dashboard/shifts/'
      preLoaderRoute: typeof DashboardShiftsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/businesses/': {
      id: '/dashboard/businesses/'
      path: '/businesses'
      fullPath: '/dashboard/businesses/'
      preLoaderRoute: typeof DashboardBusinessesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/shifts/': {
      id: '/api/shifts/'
      path: '/api/shifts'
      fullPath: '/api/shifts/'
      preLoaderRoute: typeof ApiShiftsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/shifts/new': {
      id: '/dashboard/shifts/new'
      path: '/shifts/new'
      fullPath: '/dashboard/shifts/new'
      preLoaderRoute: typeof DashboardShiftsNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/shifts/$id': {
      id: '/dashboard/shifts/$id'
      path: '/shifts/$id'
      fullPath: '/dashboard/shifts/$id'
      preLoaderRoute: typeof DashboardShiftsIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/businesses/new': {
      id: '/dashboard/businesses/new'
      path: '/businesses/new'
      fullPath: '/dashboard/businesses/new'
      preLoaderRoute: typeof DashboardBusinessesNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/businesses/$id': {
      id: '/dashboard/businesses/$id'
      path: '/businesses/$id'
      fullPath: '/dashboard/businesses/$id'
      preLoaderRoute: typeof DashboardBusinessesIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shifts/$id/claims': {
      id: '/api/shifts/$id/claims'
      path: '/api/shifts/$id/claims'
      fullPath: '/api/shifts/$id/claims'
      preLoaderRoute: typeof ApiShiftsIdClaimsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardAvailableRoute: typeof DashboardAvailableRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardScheduleRoute: typeof DashboardScheduleRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardBusinessesIdRoute: typeof DashboardBusinessesIdRoute
  DashboardBusinessesNewRoute: typeof DashboardBusinessesNewRoute
  DashboardShiftsIdRoute: typeof DashboardShiftsIdRoute
  DashboardShiftsNewRoute: typeof DashboardShiftsNewRoute
  DashboardBusinessesIndexRoute: typeof DashboardBusinessesIndexRoute
  DashboardShiftsIndexRoute: typeof DashboardShiftsIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAvailableRoute: DashboardAvailableRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardScheduleRoute: DashboardScheduleRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardBusinessesIdRoute: DashboardBusinessesIdRoute,
  DashboardBusinessesNewRoute: DashboardBusinessesNewRoute,
  DashboardShiftsIdRoute: DashboardShiftsIdRoute,
  DashboardShiftsNewRoute: DashboardShiftsNewRoute,
  DashboardBusinessesIndexRoute: DashboardBusinessesIndexRoute,
  DashboardShiftsIndexRoute: DashboardShiftsIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  _rootErrorRoute: _rootErrorRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiShiftsIndexRoute: ApiShiftsIndexRoute,
  ApiShiftsIdClaimsRoute: ApiShiftsIdClaimsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
